export const INGREDIENT_PRICE={
    meat:50,
    cheese:40,
    bacon:30,
    salad:10
};
export const ADD_INGREDIENT='ADD_INGREDIENT';
export const DELETE_INGREDIENT='DELETE_INGREDIENT';
export const INIT_INGREDIENT ='INIT_INGREDIENT';
export const ERROR='ERROR';
export const ORDER_SUCCESS="ORDER_SUCCESS";
export const ORDER_FAILED = "ORDER_FAILED";
export const PURCHASE_BURGER_START ='PURCHASE_BURGER_START';
export const INIT_PURCHASE = 'INIT_PURCHASE';
export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED'

export const AUTH_START ='AUTH_START';
export const  AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT ='AUTH_LOGOUT'
